#!/usr/bin/env node
/**
 * coverage-map.js
 *
 * Generates docs/coverage-map.md: one row per automated test case, built
 * from what the specs actually declare, so the coverage table cannot drift
 * from the code the way a hand-maintained one does.
 *
 * Each row comes from `playwright test --list --reporter=json`:
 *   - Test case ID: the test's `test_case` annotation
 *   - Client case:  every `client_case` annotation, joined with ", "
 *   - Issue:        the test's `issue` annotation, when present
 *   - Tags:         Playwright tags such as @smoke
 *   - Spec / Test:  the file and title the test lives under
 *
 * Annotations must be declared in the test's details object, for example
 *   test('Title', { tag: '@smoke', annotation: { type: 'test_case', description: 'TC_X_001' } }, ...)
 * Annotations pushed at runtime (testInfo.annotations.push) are invisible to
 * `--list`, and those tests are reported under "Tests without a test case ID".
 *
 * Usage:
 *   node scripts/coverage-map.js            # write docs/coverage-map.md
 *   node scripts/coverage-map.js --stdout   # print instead of writing
 */
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(__filename), '..');
const OUTPUT = path.join(repoRoot, 'docs', 'coverage-map.md');

/**
 * Flatten a Playwright `--list --reporter=json` report into one entry per
 * test (deduplicated across projects).
 * @param {object} report - Parsed JSON report
 * @returns {{file: string, title: string, testCase: string|null, issue: string|null, clientCases: string[], tags: string[], projects: string[]}[]}
 */
export function collectTests(report) {
  const byKey = new Map();

  function walk(suite, titles) {
    const nextTitles = suite.title && !suite.title.endsWith('.js') ? [...titles, suite.title] : titles;
    for (const spec of suite.specs || []) {
      for (const test of spec.tests || []) {
        const annotations = test.annotations || [];
        const find = type => annotations.find(a => a.type === type)?.description ?? null;
        const filterAll = type => {
          const results = [];
          const seen = new Set();
          for (const a of annotations) {
            if (a.type === type && a.description && !seen.has(a.description)) {
              results.push(a.description);
              seen.add(a.description);
            }
          }
          return results;
        };
        const key = `${spec.file}::${[...nextTitles, spec.title].join(' › ')}`;
        const entry = byKey.get(key) || {
          file: spec.file,
          title: [...nextTitles, spec.title].join(' › '),
          testCase: find('test_case'),
          issue: find('issue'),
          clientCases: filterAll('client_case'),
          tags: spec.tags || [],
          projects: [],
        };
        if (test.projectName && !entry.projects.includes(test.projectName)) {
          entry.projects.push(test.projectName);
        }
        byKey.set(key, entry);
      }
    }
    for (const child of suite.suites || []) walk(child, nextTitles);
  }

  for (const suite of report.suites || []) walk(suite, []);
  return [...byKey.values()];
}

/**
 * Render the coverage map as Markdown.
 * @param {ReturnType<typeof collectTests>} tests - Collected tests
 * @returns {string} Markdown document
 */
export function renderMarkdown(tests) {
  const cell = s => String(s).replace(/\|/g, '\\|');
  const issueCell = url => {
    if (!url) return '—';
    const number = url.match(/\/issues\/(\d+)$/);
    return number ? `[#${number[1]}](${url})` : cell(url);
  };
  const tagsCell = tags => (tags.length ? tags.map(t => `\`${t.startsWith('@') ? t : `@${t}`}\``).join(' ') : '—');
  const clientCasesCell = cases => (cases.length ? cases.map(c => cell(c)).join(', ') : '—');

  const withId = tests
    .filter(t => t.testCase)
    .sort((a, b) => a.testCase.localeCompare(b.testCase, 'en', { numeric: true }));
  const withoutId = tests.filter(t => !t.testCase);

  const lines = [
    '# Coverage map',
    '',
    '<!-- Generated by scripts/coverage-map.js (npm run coverage). Do not edit by hand. -->',
    '',
    `${withId.length} automated test case${withId.length === 1 ? '' : 's'}` +
      (withoutId.length ? `, plus ${withoutId.length} test${withoutId.length === 1 ? '' : 's'} without a test case ID.` : '.'),
    '',
  ];

  if (withId.length) {
    lines.push('| Test case | Client case | Issue | Tags | Spec | Test |', '|---|---|---|---|---|---|');
    for (const t of withId) {
      lines.push(`| ${cell(t.testCase)} | ${clientCasesCell(t.clientCases)} | ${issueCell(t.issue)} | ${tagsCell(t.tags)} | \`${cell(t.file)}\` | ${cell(t.title)} |`);
    }
    lines.push('');
  }

  if (withoutId.length) {
    lines.push('## Tests without a test case ID', '', '| Spec | Test |', '|---|---|');
    for (const t of withoutId) lines.push(`| \`${cell(t.file)}\` | ${cell(t.title)} |`);
    lines.push('');
  }

  return lines.join('\n');
}

function listTests() {
  const env = { ...process.env };
  delete env.PLAYWRIGHT_JSON_OUTPUT_NAME;
  delete env.PLAYWRIGHT_JSON_OUTPUT_FILE;
  const result = spawnSync('npx', ['playwright', 'test', '--list', '--reporter=json'], {
    cwd: repoRoot,
    env,
    encoding: 'utf8',
    maxBuffer: 1024 * 1024 * 50,
  });
  if (result.error || result.status !== 0) {
    console.error('FAIL: `playwright test --list --reporter=json` did not succeed.');
    console.error(result.error || result.stderr || result.stdout);
    process.exit(1);
  }
  return JSON.parse(result.stdout);
}

function main() {
  const markdown = renderMarkdown(collectTests(listTests()));
  if (process.argv.includes('--stdout')) {
    process.stdout.write(markdown);
    return;
  }
  fs.writeFileSync(OUTPUT, markdown);
  console.log(`Wrote ${path.relative(repoRoot, OUTPUT)}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === __filename) {
  main();
}
